# USV Processing notebook for running detection
Before running the cells in this notebook, please refer to this checklist:

- Activate usvprocessing environment prior to running code -- load from environment.yml
- Ensure the session files stored on your local device are:
    - in the correct format
    - located in the _wavfiles_ folder

# 1. Initial Setup
This section only needs to be run __once__
## Load imports

In [29]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [30]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import os

import usv_library as ul
import usv_class as uc
from usv_class import USV
import setup

### Establish path names

In [31]:
# Set path variables:
repo_path = os.getcwd()
USV_DATA_path = os.path.join(repo_path, 'USV_DATA')
wavfiles_path = os.path.join(repo_path, 'wavfiles')

## Set personal parameters

Run __once__ at the beginning of your validation/extraction session
> In this step you will:
- Set your rater ID (first and last inital)
- Set your desired frequency range

#### Select frequency range from the following options:
>A) 20 kHz (20,000 --> 30,000 Hz)  
>B) 40 kHz (40,000 --> 90,000 Hz)

In [32]:
# Set rater ID
rater_id = setup.enter_rater_id()

# Set frequency range and parent directory
usv_type = setup.enter_usv_type()
params = setup.get_params(repo_path, usv_type)
display(params)

params_file = setup.choose_params(params)

print(f"You have selected the following parameter file: {params_file}")

Rater ID set to: SN
USV type set to: 25kHz

                    default_params
0  25kHz_with_no_trial_starts.json
1     25kHz_with_trial_starts.json
2  25kHz_with_trial_starts_V2.json

You have selected the following parameter file: 25kHz_with_trial_starts_V2.json

### View sessions with local data

In [48]:
# View session folders in wavfiles directory for easy access
pd.set_option('display.max_colwidth', None)
pd.DataFrame({"session_folder":
              [subdir for subdir in os.listdir(wavfiles_path) if os.path.isdir(os.path.join(wavfiles_path, subdir))]}).sort_values('session_folder')

                                                       session_folder
2                 SK1aFM04_Restrainer_Experiment_Other_d6_s1_04252025
5     SK1aSK1b_Restrainer_Experiment_Divided_d3_s2_04222025_nontether
7              SK1aSk1b_Restrainer_Experiment_cagemate_d1_s1_04172025
11                SK2aSK1b_Restrainer_Experiment_Other_d5_s1_12022025
15             SK2aSK2b_Restrainer_Experiment_Cagemate_d1_s1_11252025
3               SK2aSK2b_Restrainer_Experiment_Divided_d4_s1_11282025
19     SK3aSK1b_Restrainer_Experiment_Other _d6_s1_06272025_nontether
4            SK3aSK3b_Restrainer_Experiment_Cagemate2 _d9_s1_07042025
17             SK3aSK3b_Restrainer_Experiment_Cagemate_d1_s2_06202025
14              SK3aSK3b_Restrainer_Experiment_Divided_d3_s1_06242025
13    SK3bSK3a_Restrainer_Experiment_Divided_d6_s1_05142025_nontether
16              SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025
18                SK4aSK1a_Restrainer_Experiment_Other_d3_s1_05202025
0             SK4aSK4b_Restrainer_Experiment_Cagemate2_d8_s1_05282025
8              SK4aSK4b_Restrainer_Experiment_Cagemate_d2_s1_05162025
6               SK4aSK4b_Restrainer_Experiment_Divided_d4_s1_05212025
12      SK5aSK1b_Restrainer_Experiment_Other_d6_s2_04232025_nontether
1   SK5aSK5b_Restrainer_Experiment_Cagemate2_d8_s1_04252025_nontether
9     SK5aSK5b_Restrainer_Experiment_Divided_d5_s1_04222025_nontether
10               Sk5aSK5b_Restrainer_Experiment_Cagemate_d2_s1_041625

---
<div style="text-align: center;">

> 
#### Only run the above code once! (Unless you are switching the frequency range you are validating or resetting your ID)

# 2. Execution

## Enter the session ID and verify WAV file exists

In [78]:
# Session ID entry
session_id = setup.get_input("Session ID", "Enter the session name: ")
print(f"Session ID entered: {session_id} \n")

# Look for WAV file -- both detection and verification need it
wavfile = os.path.join(wavfiles_path, session_id, "Dodotronic Track.wav")
if not os.path.exists(wavfile):
    raise FileNotFoundError(f"WAV file not found, cannot continue. Missing: {wavfile}")
else:
    print(f"WAV file found: {wavfile}")
    print("Open in Audacity")

trial_starts, trial_starts_rater = setup.get_trial_starts(wavfiles_path, session_id)

Session ID entered: SK1aFM04_Restrainer_Experiment_Other_d6_s1_04252025

WAV file found: /Users/sophieneale/Code/projects_work/usv_detection/wavfiles/SK1aFM04_Restrainer_Experiment_Other_d6_s1_04252025/Dodotronic Track.wav
Open in Audacity
Trial starts file found.

In [79]:
# Ensure there's a trial starts file if needed
if "with_trial_starts" in params_file:
    if trial_starts is None:
        raise FileNotFoundError("Parameter file indicates trial starts are needed, but no trial starts file was found.")

In [80]:
USV_DATA_subpath = os.path.join(USV_DATA_path, session_id, usv_type, params_file.split('.')[0])
session_subpath = os.path.join(session_id, usv_type, params_file.split('.')[0])

## Detection/validation
#### Open the WAV file in Audacity and run the next section
What do the following code blocks do?
- Check if labels already exist for your chosen file
    - If so: move onto validation
    - If not: run detection

In [81]:
# Check if session has been processed before: check for labels / rater
session_path, empty = setup.path_lookup(USV_DATA_subpath)

if empty:
    print(f"No existing data found for session {session_id} with parameters {params_file}.")
    labels_exist = False
else:
    labels_exist = setup.search_labels(USV_DATA_subpath, session_id)
    existing_rater = setup.check_existing_rater(USV_DATA_subpath, session_id, rater_id)

Path exists: /Users/sophieneale/Code/projects_work/usv_detection/USV_DATA/SK1aFM04_Restrainer_Experiment_Other_d6_s1_04252025/25kHz/25kHz_with_trial_starts_V2
Path folder is not empty. Check contents to avoid overwriting existing data.
Path exists: /Users/sophieneale/Code/projects_work/usv_detection/USV_DATA/SK1aFM04_Restrainer_Experiment_Other_d6_s1_04252025/25kHz/25kHz_with_trial_starts_V2
Path folder is not empty. Check contents to avoid overwriting existing data.
Audacity labels found.
Labels file: SK1aFM04_Restrainer_Experiment_Other_d6_s1_04252025_USV_aud.txt
Existing rater data will be overwritten.

In [82]:
# Checks if labels exist before running USV detection
if not labels_exist:
    if trial_starts is not None:
        trial_starts_file = os.path.join('wavfiles/', session_id, trial_starts)
        offset = setup.get_offset(trial_starts_file)
        print(f"Offset applied: {offset} seconds")
        usv = USV(wavfile, session_id, trial_starts_file, offset)
    else:
        usv = USV(wavfile, session_id)

    usv.set_default_params(params_file)
    usv.run_usv_detection(USV_DATA_subpath)

    print(f"Labels saved as: {session_id}_USV_aud.txt")

In [83]:
if not existing_rater:
    raise Exception(f"{session_id} has already been rated by {rater_id}.")

if not input("Proceed to USV validation/sorting? (y/n): ").lower().startswith('y'):
    raise Exception("Process terminated by user.")

# Runs sorting/validation on USV data (preexisting or newly detected)
usv_csv = os.path.join(USV_DATA_subpath, f"{session_id}_USV.csv")
call_lst = ul.validate_usv(usv_csv, usv_type)
pd.DataFrame(call_lst).to_csv(os.path.join(USV_DATA_subpath, "rated", f"{session_id}_USV_{rater_id}.csv"), index=False)
print("USV validation/sorting complete. Rated file added to session folder.")

Invalid input. Enter 1, 2, 'skip', or 'exit'.
Invalid input. Enter 1, 2, 'skip', or 'exit'.
Exiting the sorting process.
USV validation/sorting complete. Rated file added to session folder.

# 3. Finishing Protocol: push your progress!
At the end of a detection/validation session, please push new files to GitHub. 
> __NOTE:__ You should not `git push` your results every time you score, just `git push` at the end of your session.  

The command sequence is outlined here:  

    git add USV_DATA  
    git commit -m "<your message>"  
    git push