# USV Processing notebook for running detection
Before running the cells in this notebook, please refer to this checklist:

- Activate usvprocessing environment prior to running code -- load from environment.yml
- Ensure the session files stored on your local device are:
    - in the correct format
    - located in the _wavfiles_ folder

# 1. Initial Setup
This section only needs to be run __once__
## Load imports

In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [3]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import os

import usv_library as ul
import usv_class as uc
from usv_class import USV
import setup

### Establish path names

In [4]:
# Set path variables:
repo_path = os.getcwd()
USV_DATA_path = os.path.join(repo_path, 'USV_DATA')
wavfiles_path = os.path.join(repo_path, 'wavfiles')

## Set personal parameters

Run __once__ at the beginning of your validation/extraction session
> In this step you will:
- Set your rater ID (first and last inital)
- Set your desired frequency range

#### Select frequency range from the following options:
>A) 20 kHz (20,000 --> 30,000 Hz)  
>B) 40 kHz (40,000 --> 90,000 Hz)

In [ ]:
# Set rater ID
rater_id = setup.enter_rater_id()

# Set frequency range and parent directory
usv_type = setup.enter_usv_type()
params = setup.get_params(repo_path, usv_type)
display(params)

params_selection = setup.choose_params(params)

print(f"You have selected the following parameter file: {params_selection}")

Rater ID set to: SN
USV type set to: 25kHz

                    default_params
0  25kHz_with_no_trial_starts.json
1     25kHz_with_trial_starts.json

You have selected the following parameter file: 25kHz_with_no_trial_starts.json

### View sessions with local data

In [5]:
# View session folders in wavfiles directory for easy access
pd.set_option('display.max_colwidth', None)
pd.DataFrame({"session_folder":
              [subdir for subdir in os.listdir(wavfiles_path) if not subdir.endswith('.txt')]})

                                                    session_folder
0                                                        .DS_Store
1                                                         .gitkeep
2    SK5aSK1b_Restrainer_Experiment_Other_d6_s2_04232025_nontether
3  SK3bSK3a_Restrainer_Experiment_Divided_d6_s1_05142025_nontether
4            SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025

---
<div style="text-align: center;">

> 
#### Only run the above code once! (Unless you are switching the frequency range you are validating or resetting your ID)

# 2. Execution

## Enter the session ID and verify WAV file exists

In [ ]:
# Session ID entry
session_id = setup.get_input("Session ID", "Enter the session name: ")
print(f"Session ID entered: {session_id} \n")

# Look for WAV file -- both detection and verification need it
wavfile = os.path.join(wavfiles_path, session_id, "Dodotronic Track.wav")
if not os.path.exists(wavfile):
    raise FileNotFoundError(f"WAV file not found, cannot continue. Missing: {wavfile}")
else:
    print(f"WAV file found: {wavfile}")
    print("Open in Audacity")

trial_starts, trial_starts_rater = setup.get_trial_starts(wavfiles_path, session_id)

Session ID entered: SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025

WAV file found: /Users/sophieneale/Code/projects_work/usv_detection/wavfiles/SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025/Dodotronic Track.wav

Open in Audacity

In [ ]:
# Ensure there's a trial starts file if needed
if "with_trial_starts" in params_selection:
    if trial_starts is None:
        raise FileNotFoundError("Parameter file indicates trial starts are needed, but no trial starts file was found.")

Trial starts file found.
File name: SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025_SK.csv
Use trial starts in detection: True

In [ ]:
USV_DATA_subpath = os.path.join(USV_DATA_path, session_id, usv_type, params_selection.split('.')[0])
session_subpath = os.path.join(session_id, usv_type, params_selection.split('.')[0])

## Detection/validation
#### Open the WAV file in Audacity and run the next section
What do the following code blocks do?
- Check if labels already exist for your chosen file
    - If so: move onto validation
    - If not: run detection

In [ ]:
# Check if session has been processed before: check for labels / rater
session_path = setup.search_session(USV_DATA_path, session_id)
labels_exist = setup.search_labels(USV_DATA_path, session_id)
existing_rater = setup.check_existing_rater(USV_DATA_subpath, session_id, rater_id)

Folder for SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025 found.
Audacity labels found.
Labels file: SK3bSK3a_Restrainer_Experiment_Divided_d6_s2_05142025_USV_aud.txt
Existing rater data will be overwritten.

In [9]:
# Checks if labels exist before running USV detection
if not labels_exist:
    if trial_starts is not None:
        trial_starts_file = os.path.join('wavfiles/', session_id, trial_starts)
        offset = setup.get_offset(trial_starts_file)
        print(f"Offset applied: {offset} seconds")
        usv = USV(wavfile, session_id, trial_starts_file, offset)
    else:
        usv = USV(wavfile, session_id)

    usv.run_setup(freq_range, USV_DATA_path, freq_dir) 
    usv.run_usv_detection(freq_range)

    print(f"Labels saved as: {session_id}_USV_aud.txt")

In [10]:
if not existing_rater:
    raise Exception(f"{session_id} has already been rated by {rater_id}.")

if not input("Proceed to USV validation/sorting? (y/n): ").lower().startswith('y'):
    raise Exception("Process terminated by user.")

# Runs sorting/validation on USV data (preexisting or newly detected)
session_data = os.path.join(USV_DATA_subpath, session_id)
usv_csv = os.path.join(session_data, f"{session_id}_USV.csv")
call_lst = ul.validate_usv(usv_csv, freq_dir)
pd.DataFrame(call_lst).to_csv(os.path.join(session_data, f"{session_id}_USV_rated_{rater_id}.csv"), index=False)
print("USV validation/sorting complete. Rated file added to session folder.")

Invalid input. Enter 1, 2, 'skip', or 'exit'.
Invalid input. Enter 1, 2, 'skip', or 'exit'.
Invalid input. Enter 1, 2, 'skip', or 'exit'.
Exiting the sorting process.
USV validation/sorting complete. Rated file added to session folder.

# 3. Finishing Protocol: push your progress!
At the end of a detection/validation session, please push new files to GitHub. 
> __NOTE:__ You should not `git push` your results every time you score, just `git push` at the end of your session.  

The command sequence is outlined here:  

    git add USV_DATA  
    git commit -m "<your message>"  
    git push